### ISSUE TITLE
Chance of an update to add new Amiibo images?

### ISSUE THREAD

**Issue by teknomedic** [DarkIrata/AmiiboSN-Changer#5]
Hope this finds you well, It's been a few years....

Just curious if there's a chance for an update to add newer Amiibo images and perhaps add a way to edit some of the Amiibo data such as "nickname" or "mii owner".

Also, curious if there's a chance to add a "bin to NFC" file converter to this.  I personally use a FlipperZero to emulate Amiibo and that uses NFC files.  The bins can be converted using a python script such as this one: https://github.com/0xz00n/FlipMiibo ...but looking for an "all in one" solution and this already has a nice GUI.

**Comment by DarkIrata** [comment]
Hi!
Adding the images will take a little bit since the used library isn't maintained anymore, so i will have to tweak it
For the FlipperZero convertion. Yeah sure, this would be totally be possible to be added.  :)

I will look into everything and check what i can do.

**Comment by teknomedic** [comment]
Wow, fantastic.  Thank you so much.  Maybe having the ability for users to add their own images would make things easier in the long run?

Also, I actual tracked down a better Python script on github after posting the above link.  I'll add it here after I get home (don't seem to have the history on my phone).  The new script is able to convert between various formats so maybe that will be helpful or the author of the script will assist or give permission in it's use.

**Comment by teknomedic** [comment]
Here's the better script for converting Amiibo formats...
https://github.com/Lanjelin/AmiiboConverter

**Comment by DarkIrata** [comment]
> Maybe having the ability for users to add their own images would make things easier in the long run?

Yes, but i will change it to support AmiiboApi so it can update its information by itself or use a file in the api format. 
This will mean there will be more changes to the gui and it will take a little bit. 

After that, i will try to convert the python code to c# and make it a build in feature.

**Comment by teknomedic** [comment]
I didn't even expect a reply to the request so there's zero rush, but your work and this app are highly appreciated.  Looking forward to seeing what you come up with!

**Comment by teknomedic** [comment]
I didn't even expect a reply to the request so there's zero rush, but your work and this app are highly appreciated.  Looking forward to seeing what you come up with!

**Comment by DarkIrata** [comment]
You can now check out Version 3 https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/3.0.0.0
Would be happy to hear feedback for the flipper nfc file support.

**Comment by teknomedic** [comment]
Wow, it's looking great, love the dark mode!  I didn't expect something so quickly either.  I'll try and test the NFC files soon and update you.  I only had one CTD on the "self contained" version after initial setup, but since then it seems to generate bulk amiibo with no crashes both "bin to nfc" and "nfc to bin".

After playing around a little, I've only come up with two minor ideas...
First one is having a toggle option to have "leading numbers" vs "trailing numbers" on bulk exports... right now I get Amiibo_asnc_0.nfc, Amiibo_asnc_1.nfc, etc.  Would be helpful on FlipperZero (due to the small screen) to get something like 001_Amiibo_asnc.nfc, 002_Amiibo_asnc.nfc, etc.   This would also solve how FlipperZero sorts files as well... as it goes the classic 1, 10, 11, 12.... 2, 20, 21... 3, 30, etc pattern when it comes to numbers.

Also, I've run into some Amiibo that have the "user data" and "Mii" sections red and "locked" while others are green and "unlocked" for editing.  Is there a reason for this or a way to "lock/unlock" them with a button?

That all said, the program "as is" in v3 is already fantastic and could be left alone.

I can't express enough how much I appreciate your hard work and this updated app.

**Comment by teknomedic** [comment]
One more thing noted, I'm not able to type in a number amount for generated Amiibo in bulk export.  Such as getting to 50 means clicking the up arrow 50x instead of using to keyboard to enter 50.

**Comment by teknomedic** [comment]
ISSUE FOUND - Tested "Bulk Export".  Tested both "BIN to NFC" and "NFC to NFC".  Set bulk export to 10 for each Amiibo type and ended up with 20 files total.  None had randomized serials so once I tested the first one, all other's were seen as the same one and can't be used for 24 hours.  Seems I'd have to generate a serial using the "refresh" button, generate a single amiibo, then rinse/repeat.

I also tested the individual "export" option and hit the "serial refresh button" on each single creation, this worked correctly with all Amiibo getting unique serials all being used in game without issue.  I test both BIN to NFC and NFC to NFC and it works properly on all attempts.

So it seems "Bulk Export" is simply not generating new serials during it's operation.

**Comment by DarkIrata** [comment]
Thanks for the feedback!
Couldn't reproduce the Self Contained crash but the other things were easy to fix :)
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v3.0.1

**Comment by teknomedic** [comment]
All the fixes are fixed, ha.  Very nice work.  I did find a new problem though...

ISSUE FOUND - I think it stems from this update **_"Bulk Export Settings are now reused"_**.  Now it remembers too well, ha.  Basically it will remember which amiibo were first loaded even after deleting them from the main screen (or even physically from the folder) and trying to copy another amiibo.  The only way to fix this is to close the program and reload.

Examples:
Amiibo-1, Amiibo-2, & Amiibo-3 are loaded into program via "load tag" or "drag and drop".  I then use bulk export and generate 10x of each amiibo.  I then delete all three from the tag window and load Amiibo-4.  I then bulk export again and Amiibo-4 is ignored, BUT... I get 10 new copies each of Amiibo-1, Amiibo-2, & Amiibo-3 again.

This happens doing only one at a time as well.  If I load Amiibo-1, bulk export, delete Amiibo-1 and then load Amiiibo-2 I get more copies of Amiibo-1 again.

Also, also... the program will generate the first loaded Amiibo again even if I physically delete the Amiibo files from the original folder.  All I need to do is load Amiibo-4 to "unlock" the export functions and then the program will re-clone the previous ones ignoring Amiibo-4 once again, ha.

Once again your hard work is greatly appreciated.
(edit, also, any chance of a "delete all" or "clear tags" button to wipe all Amiibo at the same time vs clicking on each "delete" button one at a time?)

**Comment by DarkIrata** [comment]
Should have tested it with different amiibos than just 2 Link Amiibos.. 😅  should be fixed now.
And yeah.. a clear button makes total sense. Also added it!
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v3.0.2
Clear button not activating on drag and drop is already known.. and will be patched later

**Comment by teknomedic** [comment]
I think you got it, ha.  All my tests worked great.  Clear button issue not withstanding of course. :)

That initial CTD still happens with each new version, but it never happens again after first load.  Here are the steps I'm taking each time in case you want to dig into it more.  I'm running Windows 10.

----
Steps for crash to desktop = (must keep program running on first run)
download "self contained", extract files, load app, load retail key, check the boxes, update DB, download all images, save... next I load a tag, then bulk export... set my folder, check all boxes, set number to 50, set type to NFC and hit "export"... slight hang then CTD happens, no Amiibo created.

Again, only the very first run and only if I don't close the app at all during the first run.

If I set settings, close the app then reload and then do bulk exports no issues.  Also, once the first CTD happens, haven't seen another one while running the app.  So seems to have something to do with initial settings maybe conflicting during a "save settings & export amiibo" at the same time situation.

----
I think the program is essentially done and I really, REALLY appreciate the new version!  I'll be spreading the word about it where ever it makes sense to do so.

Only other suggestions I have now are just personal wish list items and have zero need, but in case you're curious...
1) Using spaces vs underscores in file names.

2) Being able to set the name of the exported files manually before export (would probably only work on regular export and not "bulk export" as I don't see an easy way to set individual names of 20+ tags, ha).

3) When exporting multiple amiibo/tags in bulk export, have it create new subfolders for each set of tags with the file name... so if I loaded 10 tags and then bulk exported 30 per tag, I'd get 10 folders named after their tags, then inside the folders have the respective 30 tags.

4) When loading tags, default to looking for "all file types" or "bin & nfc".  Currently defaults to just looking for BIN files meaning each time I need to load NFC files I have to also change what the program looks for.

That's about all I got.  Also, do you have a Patreon or donation page?  I feel like I owe you a coffee at least. :)

**Comment by DarkIrata** [comment]
I only could reproduce it with 3.0.1. Just to be sure changed a few Build Settings.
For the other ideas, i resolved multiple with a single ui change, so why not :D
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v3.0.3

**Comment by teknomedic** [comment]
Wow! You added them all? lol.  Thank you!
You did far more than I expected.  Also, no more crashes to the desktop, so you fixed that as well.  Fantastic work!

----
Only two things I noticed/thought of...

1) The new tag subfolders are being named by the internal tag name and not the tag's file name or the custom name I set, certainly not a big deal and I can see pros and cons to doing it either way.
**_Example - Tag file name is "Toon Zelda.BIN", Internal tag name is "WWaker ToonZ".  I set output names to be "NUM FILE (Wind Waker) (ASNC).NFC".  The created subfolder is named "WWaker ToonZ"._**
If you're up for it one day a toggle option for "use custom name for subfolders" to get a subfolder called "Toon Zelda (Wind Waker) (ASNC)" could be useful.  Certainly not required though.

2) Also, the default directory that the program loads when "load tag" is used seems to be whatever was last used by the program.  So if I load TAG1 from XYZ directory and export to 123 directory.  If I go to load a new tag it opens 123 directory instead of XYZ where my original tags are.  Again, very minor and easy to get used to.
----

These certainly aren't big problems and are only random thoughts I had while testing the new version.

Once again, just wow... and thank you for providing this fantastic tool!!

**Comment by DarkIrata** [comment]
https://github.com/DarkIrata/AmiiboSN-Changer/releases/tag/v3.0.4

The second problem was an actual bug. Since i wanted to fix it, i checked the subfolder idea and got it also to work with a caveats (<num> gets ignored).
Think at this point i will only fix bugs and get back to some other projects. Happy to hear i could improve this old tool :D

**Comment by teknomedic** [comment]
You did more than I expected.  I've not run into any other issues and really have no more ideas... Take a well deserved break from this!
